name=wikimedia-source-connector
tasks.max=1
connector.class=io.conduktor.demos.kafka.connect.wikimedia.WikimediaConnector
topic=wikimedia.recentchange.connect
url=https://stream.wikimedia.org/v2/stream/recentchange
http.headers.user.agent=WikimediaKafkaConnector/1.0 (https://github.com/conduktor/kafka-connect-wikimedia)
errors.tolerance=all
errors.deadletterqueue.topic.name=wikimedia.connect.dlq